---
title: Desainimasi
subtitle: ''
email: ''
description: ''
baseurl: "/"
url: 
author: 
street_address: ''
city: ''
state: ''
zip_code: ''
country: ''
phone: ''
tiles-source: pages
tiles-count: "6"
500px_url: 
facebook_url: 
github_url: 
gitlab_url: ''
googleplus_url: ''
instagram_url: https://instagram.com/desainimasi
linkedin_url: ''
pinterest_url: 
slack_url: 
twitter_url: ''
markdown: kramdown
sass:
  style: compressed
